import http from './http'

export const getDashboard = () => http.get('/admin/dashboard')
export const getAdminProducts = () => http.get('/admin/products')
export const createProduct = (payload) => http.post('/admin/products', payload)
export const updateProduct = (id, payload) => http.put(`/admin/products/${id}`, payload)
export const deleteProduct = (id) => http.delete(`/admin/products/${id}`)
export const getAdminOrders = () => http.get('/admin/orders')
export const shipOrder = (id) => http.patch(`/admin/orders/${id}/ship`)
export const getOperationBoard = () => http.get('/admin/operation-board')
export const getMarketing = () => http.get('/admin/marketing')
export const createMarketing = (payload) => http.post('/admin/marketing', payload)
export const getConfigs = () => http.get('/admin/configs')
export const updateConfig = (key, payload) => http.put(`/admin/configs/${key}`, payload)
export const getRiskItems = () => http.get('/admin/risk')
export const resolveRisk = (id) => http.patch(`/admin/risk/${id}/resolve`)
export const getReports = () => http.get('/admin/reports')
export const getHighConcurrency = () => http.get('/admin/high-concurrency')
export const createSeckillEvent = (payload) => http.post('/admin/seckill-events', payload)
