import http from './http'

export const login = (payload) => http.post('/auth/login', payload)
export const register = (payload) => http.post('/auth/register', payload)
export const getCategories = () => http.get('/categories')
export const getProducts = (keyword, categoryId) => http.get('/products', { params: { keyword, categoryId } })
export const getProduct = (id) => http.get(`/products/${id}`)
export const getCart = () => http.get('/cart')
export const addCart = (payload) => http.post('/cart', payload)
export const updateCart = (id, quantity) => http.put(`/cart/${id}`, { quantity })
export const removeCart = (id) => http.delete(`/cart/${id}`)
export const checkout = (shippingAddress) => http.post('/orders/checkout', { shippingAddress })
export const getOrders = () => http.get('/orders')
export const payOrder = (id) => http.patch(`/orders/${id}/pay`)
export const cancelOrder = (id) => http.patch(`/orders/${id}/cancel`)
export const receiveOrder = (id) => http.patch(`/orders/${id}/receive`)
export const getAddresses = () => http.get('/addresses')
export const saveAddress = (payload) => http.post('/addresses', payload)
export const deleteAddress = (id) => http.delete(`/addresses/${id}`)
export const getCoupons = () => http.get('/coupons')
export const claimCoupon = (id) => http.post(`/coupons/${id}/claim`)
export const getFavorites = () => http.get('/favorites')
export const favoriteProduct = (id) => http.post(`/favorites/${id}`)
export const unfavoriteProduct = (id) => http.delete(`/favorites/${id}`)
export const getProductReviews = (id) => http.get(`/products/${id}/reviews`)
export const addProductReview = (id, payload) => http.post(`/products/${id}/reviews`, payload)
export const getProductQuestions = (id) => http.get(`/products/${id}/questions`)
export const askProductQuestion = (id, payload) => http.post(`/products/${id}/questions`, payload)
export const getMemberProfile = () => http.get('/member/profile')
export const getMemberMessages = () => http.get('/member/messages')
export const readMessage = (id) => http.patch(`/member/messages/${id}/read`)
export const getLogistics = (id) => http.get(`/orders/${id}/logistics`)
export const requestAfterSale = (id, payload) => http.post(`/orders/${id}/after-sales`, payload)
export const getAfterSales = () => http.get('/after-sales')
export const getSeckillEvents = () => http.get('/seckill-events')
export const purchaseSeckill = (id) => http.post(`/seckill-events/${id}/purchase`)
